defaults:
  - default.yaml

accelerator: cpu  # run on CPU only (might be really slow, but change it if necessary)
benchmark: False  # turn benchmark mode off, we don't need crazy performance here
deterministic: True  # ... and of course, we'd like each session to behave the same as the last
max_epochs: 2  # run a single epoch by default (other debug configs might try overfit instead)
limit_train_batches: 5  # run at most 5 batches per training epoch
limit_val_batches: 5  # run at most 5 batches per validation epoch
limit_test_batches: 5  # run at most 5 batches per testing epoch
num_sanity_val_steps: 1  # run through a single validation batch before training

devices: 1  # debuggers don't like multi-device setups, let's not use anything fancy here
detect_anomaly: True  # raise an exception if NaN or +/-inf is detected in any tensor
track_grad_norm: 2  # track gradient norm with loggers
precision: 32
