defaults:
  - default.yaml
  - _self_

lr_monitor:
  _target_: lightning.pytorch.callbacks.LearningRateMonitor
  # https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.callbacks.LearningRateMonitor.html
