# @package _global_
#
# This root config is associated to the 'train.py' entrypoint provided with the framework.
#
# Note: when launching with this config, you likely need an experiment subconfig! For example:
#     python train.py experiment=example_mnist_classif
#
# To change the output folder location, see the output/default.yaml definitions.

defaults:
  - _self_
  - utils: default.yaml # utility configs contain general-use-but-not-so-important settings
  - output: default.yaml # output configs define the root path and name patterns to use for logging
  - data: default.yaml # data configs define the datamodule and dataloaders to instantiate
  - model: default.yaml # model configs define the LightningModule-derived models to instantiate
  - callbacks: default.yaml # callbacks configs define which lightning callbacks will be enabled
  - logger: default.yaml # logger configs define what kind of logging to use (e.g. MLFlow, wandb)
  - trainer: default.yaml # trainer configs define the (lightning-derived) trainer to instantiate
  - experiment: null # experiment configs allow for overrides and version control of all settings
  - hparams_search: null # hyperparameter search configs allow for control of sweep settings
  - optional local: default.yaml # optional overriding config for machine/user specific settings
  - debug: null # debugging configs allow for extra logging and deactivation of optimization stuff

resume_from_latest_if_possible: True # toggles whether to reload latest ckpt, always, if possible
experiment_name: default # defines the experiment name used in various output/logging paths
run_type: train-valid # defines whether to train, validate, test, or any combo of those
run_name: ${utils.curr_timestamp} # defines the run name used in various output/logging paths
job_name: ${oc.select:hydra.job.num,0} # defines the job name used in various output/logging paths

utils:
  seed: 1 # run with a fixed seed (at least at first, might help find bugs)
  seed_workers: True # also fix that seed across all data loader workers
