# NOTE: THIS FILE IS UNUSED (AND ORIGINALLY FROM THE TEMPLATE) AS OF 2022-06-25

_target_: ssl4rs.models.mnist_module.MNISTLitModule
lr: 0.001
weight_decay: 0.0005

net:
  _target_: ssl4rs.models.components.simple_dense_net.SimpleDenseNet
  input_size: 784
  lin1_size: 256
  lin2_size: 256
  lin3_size: 256
  output_size: 10
