defaults:
  - default.yaml
  - _self_

lr_monitor:
  _target_: pytorch_lightning.callbacks.LearningRateMonitor
  # https://pytorch-lightning.readthedocs.io/en/stable/api/pytorch_lightning.callbacks.LearningRateMonitor.html
