# @package _global_

defaults:
  - _self_  # loads the parameters from down below first, and allows them to be overridden if needed
  - utils: default.yaml  # utility configs contain general-use-but-not-so-important settings
  - output: default.yaml  # output configs define the root path and name patterns to use for logging
  - data: mnist.yaml  # data configs define the datamodule to instantiate
  - model: mnist.yaml  # model configs define the model to instantiate
  - callbacks: default.yaml  # callbacks configs define pytorch lightning callbacks to be enabled
  - logger: null  # logger configs define what kind of logging to use (e.g. MLFlow, wandb, ...)
  - trainer: default.yaml  # trainer configs define the (lightning-derived) trainer to instantiate
  - experiment: null  # experiment configs allow for overrides and version control of all settings
  - debug: null  # debugging configs allow for extra logging and deactivation of optimization stuff
  - optional local: default.yaml  # optional overriding config for machine/user specific settings
  - override hydra/hydra_logging: colorlog
  - override hydra/job_logging: colorlog

experiment_name: default  # experiment name used in output paths (overridden in experiment configs)
run_type: test  # should always remain as 'test' unless a derivation of the testing pipeline is used
ckpt_path: ???  # MANDATORY path to the pytorch lightning checkpoint to be reloaded for testing
