# @package _global_

defaults:
  - default.yaml

trainer:
  max_epochs: 3
  limit_train_batches: 0.01  # will train using only 1% of the training data
  limit_val_batches: 0.05  # ...and validate using only 5% of the validation data
  limit_test_batches: 0.05  # ...and test using only 5% of the testing data
