# @package _global_

defaults:
  - default.yaml
  - _self_

trainer:
  max_epochs: 2
  limit_train_batches: 32
  limit_val_batches: 32
  limit_test_batches: 32
  limit_predict_batches: 32
  profiler: simple
  # https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.profilers.SimpleProfiler.html
  # profiler: advanced
  # https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.profilers.AdvancedProfiler.html
  # profiler: pytorch
  # https://lightning.ai/docs/pytorch/stable/api/lightning.pytorch.profilers.PyTorchProfiler.html
