name: Code Quality Checks

on:
  pull_request:
    branches: ["master", "release/*", "dev"]
  push:
    branches: ["master", "release/*", "dev"]

jobs:
  run_checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install pre-commit runner
        run: |
          pip install pre-commit setuptools

      - name: Run pre-commit checks on all files
        run: |
          pre-commit run -a --show-diff-on-failure
